### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'node')

### ISSUE THREAD

**Issue by HarshMB** [nomi9995/react-native-decompiler#17]
I tried to decompile index.android.bundle using below command:-

react-native-decompiler -i ./index.android.bundle -o ./output

But got Below Error:-

>TypeError: Cannot read properties of undefined (reading 'node')
    at CallExpression (/usr/local/lib/node_modules/react-native-decompiler/out/decompilers/evaluators/spreadifier.js:39:82)
    at /usr/local/lib/node_modules/react-native-decompiler/out/router.js:101:37
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/react-native-decompiler/out/router.js:101:21
    at NodePath._call (/usr/local/lib/node_modules/react-native-decompiler/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/usr/local/lib/node_modules/react-native-decompiler/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/usr/local/lib/node_modules/react-native-decompiler/node_modules/@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (/usr/local/lib/node_modules/react-native-decompiler/node_modules/@babel/traverse/lib/context.js:115:16)
    at TraversalContext.visitSingle (/usr/local/lib/node_modules/react-native-decompiler/node_modules/@babel/traverse/lib/context.js:84:19)
    at TraversalContext.visit (/usr/local/lib/node_modules/react-native-decompiler/node_modules/@babel/traverse/lib/context.js:143:19)

Please suggest me solution

**Comment by Giasinit** [comment]
have you found solution?
